apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demoapp.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_PASSWORD: TXlEYXRhYmFzZTU2Nwo=
  DJANGO_ADMIN_PASSWORD: ZGV2ZWxvcGVyCg==
