apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demoapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    {{- include "demoapp.db.selectorLabels" . | nindent 4 }}
