apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.applicationBlue.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "demoapp.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svcjenkins
  namespace: {{ .Values.namespace }}
