apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nsinfos.k8s.orcunuso.io
spec:
  additionalPrinterColumns:
  - name: Title
    description: Title of the namespace
    JSONPath: .spec.title
    type: string
  - name: Environment
    JSONPath: .spec.environment
    type: string
  - name: ServiceID
    JSONPath: .spec.serviceId
    type: string
  - name: Owner
    JSONPath: .spec.owner
    type: string
  - name: Age
    JSONPath: .metadata.creationTimestamp
    type: date
  group: k8s.orcunuso.io
  names:
    kind: NSInfo
    listKind: NSInfoList
    plural: nsinfos
    singular: nsinfo
    shortNames:
    - nsi
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          description: Spec for NS Information
          required: ["title","environment","owner"]
          type: object
          properties:
            title:
              description: Title of the namespace
              type: string
            environment:
              description: Environment, prod or test
              type: string
            serviceId:
              description: ID in the CMDB
              type: string
            owner:
              description: Owner of the namespace
              type: string