kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "kind.orcunuso.io"
  apiServerPort: 6443
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.configs."harbor.orcunuso.io".tls]
    insecure_skip_verify = true
nodes:
- role: control-plane
  image: harbor.orcunuso.io/demoapp/kind-node:v1.18.2
- role: control-plane
  image: harbor.orcunuso.io/demoapp/kind-node:v1.18.2
- role: control-plane
  image: harbor.orcunuso.io/demoapp/kind-node:v1.18.2
- role: worker
  image: harbor.orcunuso.io/demoapp/kind-node:v1.18.2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP