name: CI Workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Set environment variable
      run: echo "::set-env name=BUILDIMAGE::no"
    - name: Build and push docker image
      if: env.BUILDIMAGE == 'yes'
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: orcunuso/demoapp
        tags: v0
        push: true

# https://github.com/docker/build-push-action
